version: "1"

services:
  # BACKEND FLASK
  - type: web
    name: backend-flask
    runtime: python:3.10.12
    plan: free
    region: frankfurt
    repo: https://github.com/gabrieladamasuam/7311-02-P1C
    rootDir: backend-flask
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:api --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: videogames-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true

  # FRONTEND (VITE â€“ STATIC)
  - type: web
    name: frontend-videogames
    env: static
    repo: https://github.com/gabrieladamasuam/7311-02-P1C
    rootDir: frontend-videogames
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://backend-flask.onrender.com

databases:
  - name: videogames-db
    plan: free
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere